version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      EXOHUNTER_CELERY_BROKER_URL: redis://redis:6379/0
      EXOHUNTER_CELERY_RESULT_BACKEND: redis://redis:6379/1

  celery_worker:
    build: .
    command: celery -A exohunter.celery_app worker --loglevel=info --concurrency=4
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
