version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: exohunter_queue_broker
    ports:
      - "6379:6379"
    restart: always

  celery_worker:
    build: .
    container_name: exohunter_physics_worker
    command: celery -A exohunter.celery_app worker --loglevel=info --concurrency=4
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
    restart: always
